### ISSUE TITLE
Add a example file

### ISSUE THREAD

**Issue by SwayStar123** [open-spaced-repetition/fsrs-rs#144]
It would be helpful to have a example file with a single demonstration of how the library is meant to be used

**Comment by L-M-Sherlock** [comment]
You can refer to https://github.com/ankitects/anki/blob/55ef11af84151b397f267a2f37d537aad5f1076d/rslib/src/scheduler/answering/mod.rs#L363-L410

**Comment by syt0r** [comment]
I second this. If possible I want to refer to the most maintained library to implement FSRS in my app but it's hard to understand what's going on in the code, what values should be saved. And because I'm not familiar with Rust and internals of Anki it looks even extra complicated 😓. Having a small sample in README how to create new cards and get intervals for different grades would be really helpful

**Comment by L-M-Sherlock** [comment]
The well-documented package of FSRS is ts-fsrs: https://github.com/open-spaced-repetition/ts-fsrs

**Comment by syt0r** [comment]
Thanks, that one is great
